import type {
  BitrixChatMessageRaw,
  BitrixChatUserRaw,
  BitrixTaskCommentRaw,
} from '~/server/types/bitrix24'
import { pick, toNumber } from '~/server/utils/wire-coerce'

/**
 * Pure parser for `task.commentitem.*` response items. Mirrors what
 * `toTaskShort` / `toChecklistItemShort` / `toElapsedTimeShort` do for their
 * domains: narrow the agent-facing shape, coerce stringified ids, keep the
 * wire-format quirks out of the tool body.
 *
 * The comment BODY is never truncated here — reading a task's discussion is
 * the whole point of the tool, and a cut-off comment silently changes what
 * the operator is told. Callers that need to bound the response do it by
 * returning fewer comments (`limit` / `offset`), never by shortening one.
 *
 * Returns `null` when the wire shape carries no usable `id` — same fail-soft
 * convention as the sibling parsers.
 */

export interface TaskCommentShort {
  /** Which storage the comment came from — `forum` for legacy
   *  `task.commentitem.*` rows, `chat` for task-chat messages. Both can
   *  appear in one thread on a task that predates the chat migration. */
  source: 'forum' | 'chat'
  /** `true` only when Bitrix24 provably marked the entry as generated by the
   *  system (`author_id: 0` in the chat). Chat-side lifecycle notes and the
   *  chat's own "это новый чат задачи" boilerplate get flagged. Forum rows
   *  carry no such marker, so they are always `false` — see the note in
   *  `list-task-comments.ts`; do NOT read `false` as "definitely human". */
  isSystem: boolean
  id: number
  /** Not echoed by Bitrix24 on the item — filled in by the caller. */
  taskId: number
  authorId: number | null
  /** Shipped by Bitrix24 next to the id, so "from whom" needs no extra call. */
  authorName: string | null
  authorEmail: string | null
  postDate: string | null
  /** Full BBCode body, verbatim. */
  text: string
  /** Bitrix24's pre-rendered HTML — `null` for UI-written comments. */
  textHtml: string | null
}

export function toTaskCommentShort(raw: unknown, taskId: number): TaskCommentShort | null {
  if (!raw || typeof raw !== 'object') return null
  const r = raw as BitrixTaskCommentRaw & Record<string, unknown>
  const id = toNumber(pick(r, 'id', 'ID'))
  if (id === null) return null
  return {
    source: 'forum',
    // The forum API exposes no system/human marker at all.
    isSystem: false,
    id,
    taskId,
    authorId: toNumber(pick(r, 'authorId', 'AUTHOR_ID')),
    // Empty string means "Bitrix24 has no value" for both author fields —
    // normalise to null so the agent doesn't render an empty attribution.
    authorName: pick<string>(r, 'authorName', 'AUTHOR_NAME') || null,
    authorEmail: pick<string>(r, 'authorEmail', 'AUTHOR_EMAIL') || null,
    postDate: pick<string>(r, 'postDate', 'POST_DATE') || null,
    text: pick<string>(r, 'postMessage', 'POST_MESSAGE') ?? '',
    textHtml: pick<string>(r, 'postMessageHtml', 'POST_MESSAGE_HTML') || null,
  }
}

/**
 * Parser for one `im.dialog.messages.get` message — the chat-side half of a
 * task's comment thread.
 *
 * `names` maps user id → display name, built from the `users` array of the
 * same response, so attribution needs no extra `user.get` (mirroring what
 * `AUTHOR_NAME` gives us for free on the forum side).
 *
 * `author_id: 0` is Bitrix24's system marker. It covers both the lifecycle
 * notes ("… приостановил выполнение задачи") and the boilerplate the portal
 * posts when it creates a task chat, so it is the one dependable
 * system-vs-human signal available in either storage.
 */
export function toChatCommentShort(
  raw: unknown,
  taskId: number,
  names: Map<number, string>,
): TaskCommentShort | null {
  if (!raw || typeof raw !== 'object') return null
  const r = raw as BitrixChatMessageRaw & Record<string, unknown>
  const id = toNumber(r.id)
  if (id === null) return null
  const authorId = toNumber(r.author_id)
  const isSystem = authorId === 0
  return {
    source: 'chat',
    isSystem,
    id,
    taskId,
    // A system message has author id 0, which is not a real user — report it
    // as null rather than inventing user #0.
    authorId: isSystem ? null : authorId,
    authorName: isSystem ? null : (authorId !== null ? (names.get(authorId) ?? null) : null),
    // The chat API ships no author email.
    authorEmail: null,
    postDate: typeof r.date === 'string' && r.date !== '' ? r.date : null,
    text: typeof r.text === 'string' ? r.text : '',
    // Chat messages are BBCode-ish text; Bitrix24 pre-renders nothing here.
    textHtml: null,
  }
}

/** Build the id → display-name map from an `im.dialog.messages.get` `users` array. */
export function chatUserNames(users: unknown): Map<number, string> {
  const map = new Map<number, string>()
  if (!Array.isArray(users)) return map
  for (const entry of users) {
    if (!entry || typeof entry !== 'object') continue
    const u = entry as BitrixChatUserRaw
    const id = toNumber(u.id)
    if (id === null) continue
    const name = u.name
      || [u.first_name, u.last_name].filter((part) => typeof part === 'string' && part !== '').join(' ')
    if (typeof name === 'string' && name !== '') map.set(id, name)
  }
  return map
}
